name: ci

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.2
      -
        name: Login to Docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
      -
        name: Build and push
        uses: docker/build-push-action@v5.2.0
        with:
          context: ./hello-world 
          file: ./hello-world/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-hello-world:latest
