name: ci

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout
      -
        name: Login to Docker hub
        uses: docker/login-action
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action
      -
        name: Build and push
        uses: docker/build-push-action
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-hello-world:latest
